spring:
  application:
    name: shopping-cart
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
    loadbalancer:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

server:
  port: 0

warehouse:
  url: http://10.1.0.23:42327

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
      WAREHOUSE:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: DEBUG
    ru.yandex.practicum.commerce.client: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    com.netflix.loadbalancer: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG